name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile
        run: pnpm prestart

      - name: ESLint & Prettier
        run: pnpm lint

      - name: Tests
        run: pnpm test
      
      # TODO: write
      # - name: Tests
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: npm test

      # - name: Upload coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #   with:
      #     coverageLocations: ${{github.workspace}}/src/dist/coverage/lcov.info:lcov